# Default values for ubuntu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ubuntu
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
