apiVersion: v2
name: mockserver
version: 1.1.0
keywords:
  - mockserver
description: A Helm chart for mockserver in Kubernetes
type: application
home: https://github.com/SimonMisencik/helm-charts
sources:
  - https://github.com/SimonMisencik/helm-charts/tree/main/charts/mockserver
maintainers:
  - name: SimonMisencik
    email: simon.misencik@gmail.com
icon: https://pics.freeicons.io/uploads/icons/png/18449610531586788036-512.png
appVersion: "5.15.0"
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Fix healcheck problem and add option to add containerPort
      links:
        - name: GitHub PR
          url: https://github.com/simonmisencik/helm-charts/pull/18
