apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-ubuntu
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      command: ["/bin/sleep", "3650d"]
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
