apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-ubuntu
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      args:
        - sh
        - -c
        - apt update && apt install curl -y && apt install nmap -y && touch /tmp/healthy > STATUS && sleep 365d
      imagePullPolicy: IfNotPresent
      startupProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
  restartPolicy: Always
