apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb"
  annotations:
    # This is what defines this resource as a hook. Without this 
    # line, the job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    # "helm.sh/hook-delete-policy": before-hook-creation
spec:
  mode: Single
  tls:
    caSecretName: None
  auth:
    jwtSecretName: {{ .Values.arangodb_config.tokenSecretName }}
  image: "{{ .Values.arangodb_config.image.repository }}:{{ .Values.arangodb_config.image.tag | default .Chart.AppVersion }}"
