{{- if .Values.middleware.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "basic-app.fullname" . }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.middleware.stripPrefix }}
{{- end }}
