apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-kali
  labels:
    app: kali
spec:
  containers:
    - name: kali
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      args:
        - sh
        - -c
        - apt update && touch /tmp/healthy && sleep 365d
      imagePullPolicy: IfNotPresent
      startupProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        failureThreshold: 30
        periodSeconds: 10
  restartPolicy: Always
