frinx-arangodb:
  enabled: true
  arangodb_config:
    image:
      tag: "3.9.1"
    token: 6647ee8a9129b388eabc6c788697197e0fd805346b4867a5d117f0c691c6bfc1
    bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmFuZ29kYiIsInNlcnZlcl9pZCI6ImZvbyJ9.OxGlpYQYzOysECGkonaEP8d64UH1wQeo_XxeIqK8Vgg

  arango_operator_secret:
    username: frinx
    password: frinx

kube-arangodb:
  operator:
    replicaCount: 1
    args:
    - --shutdown.delay=5m
  rbac:
    enabled: true
    extensions:
      monitoring: false
      acs: false
      at: false

  resources:
    limits:
      cpu: 1
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi