# Default values for kali.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: kalilinux/kali-rolling
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
