# Default values for basic-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ovhplatform/what-is-my-pod
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  port: 8080

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # (Optional): Annotations for the Ingress Controller
    # ---
    # General:
    # kubernetes.io/ingress.class: traefik
    #  
    # TLS configuration:
    # traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # traefik.ingress.kubernetes.io/router.tls.certresolver: "production"
    #  
    # Middleware:
    # traefik.ingress.kubernetes.io/router.middlewares: dev-test-dev-stripprefix@kubernetescrd
  hosts:
    - host: "test.com"
      paths:
        - path: /
          pathType: Prefix

middleware:
  enabled: false
  stripPrefix:
